### ISSUE TITLE
RNFSTurboModule could not be found

### ISSUE THREAD

**Issue by netdown** [cmpayc/react-native-fs-turbo#1]
Hi,

It seems that the native module is not registered on Android, my app throws an exception on startup:
 (NOBRIDGE) ERROR  Error: Failed to create a new RNFSTurbo instance.

The internal exception is:
[Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'RNFSTurboModule' could not be found. Verify that a module by this name is registered in the native binary.]

I have noticed that the android folder and react-native.config.js is missing from the npm release, I'm not sure if that's intentional or not, but manually copying them does not solve the issue.

Env:
RN 0.76.2
Npm 10
Win 10

**Comment by cmpayc** [comment]
Hi @netdown !

Thanks for pointing this out. I forgot to add the Android files to `package.json` so that they would be uploaded to npm.

I also found a problem with running the package on react-native 0.75+ (codegen generation changed). 

I have fixed these issues in the new version ([v0.1.5](https://github.com/cmpayc/react-native-fs-turbo/releases/tag/v0.1.5))
